config/routes.rb
Rails.application.routes.draw do
  # カスタマーroutes
  root 'homes#top'
  get 'home/top', to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get 'home/top_select', to: 'homes#top_select'
  devise_for :customers
  namespace :public do
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'confirm', to: 'customers#confirm'
        put "withdrawal" => "customers#withdrawal"
      end
    end
    resources :inquiries, only: [:index, :create]
    resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :groups_customers, only: [:index, :create, :destroy] do
      member do
        get 'menbers', to: 'groups_customers#members_index'
        get 'maps', to: 'groups_customers#maps_index'
        get 'key_word', to: 'groups_customers#key_word'
      end
    end
    resources :places do
      resources :likes, only: [:create, :destroy]
      member do
        get 'place_new_add', to: 'places#place_new_add'
      end
    end
    resources :place_images
  end

  # 管理者routes
  devise_for :admins
  namespace :admin do
    resources :inquiries, only: [:index, :edit, :update]
    resources :customers, only: [:index, :show] do
      member do
        get 'confirm', to: 'customers#confirm'
        put "withdrawal" => "customers#withdrawal"
      end
    end
    resources :genres, only: [:index, :edit, :create, :destroy, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :places, only: [:index, :show, :destroy]
  end

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#new_guest'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :places, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :groups_customers, dependent: :destroy

  # 3文字以上
  validates :nick_name, length: { minimum: 3 }

  # 一意性
  validates :nick_name, uniqueness: true

  # お問い合わせ
  has_many :inquiries, dependent: :destroy

  # いいね機能
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :place
  def already_liked?(place)
    likes.exists?(place_id: place.id)
  end

  # 画像アップロード機能
  attachment :image

  # 退会済みならログイン不可
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ゲストログイン用
  def self.guest
    find_or_create_by!(email: 'guest@gmail.work', nick_name: "げすと") do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :places, dependent: :destroy

  # 空白NG
  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :groups_customers, dependent: :destroy

  # 空白NG
  validates :name, presence: true
  # validates :is_closed, presence: true

  # 一意性
  validates :name, uniqueness: true
  # validates :key_word, uniqueness: true, allow_nil: true

  # 画像アップロード機能
  attachment :image

  # is_closed(非公開の場合)のみ空白NG
  with_options if: :is_closed? do
    validates :key_word, presence: true
  end
end

app/models/groups_customer.rb
class GroupsCustomer < ApplicationRecord
  belongs_to :customer
  belongs_to :group

  # 空白NG
  # validates :customer_id, presence: true
  # validates :group_id, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :customer
  enum status: { 対応待ち: 0, 対応中: 1, 対応済み: 2 }

  # 空白NG
  validates :customer_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :status, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :place

  # 空白NG
  validates :customer_id, presence: true
  validates :place_id, presence: true

  # いいね機能
  validates_uniqueness_of :place_id, scope: :customer_id
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :genre
  belongs_to :customer

  # group_idを持たなくても保存できる
  belongs_to :group, optional: true

  # 複数画像投稿用
  has_many :place_images, dependent: :destroy
  accepts_attachments_for :place_images, attachment: :image

  # 3文字以上
  validates :address, length: { minimum: 3 }

  # 空白NG
  validates :customer_id, presence: true
  validates :place_name, presence: true

  # 経度、緯度表示機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # いいね機能
  has_many :likes
  has_many :liked_customers, through: :likes, source: :customer
end

app/models/place_image.rb
class PlaceImage < ApplicationRecord
  belongs_to :place, optional: true
  # 画像投稿用
  attachment :image

  # place_idの空白NG
  validates :place_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # 新規登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    home_top_select_path
  end

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_inquiries_path
    when Customer
      home_top_select_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate, only: [:top_select]
  before_action :logind, only: [:top]
  def top
  end

  def about
  end

  def top_select
    @gorups = GroupsCustomer.where(customer_id: current_customer.id)
    @places = Place.where(customer_id: current_customer.id)
  end

  private
  # ログインしていないユーザーはTOPページに遷移
  def authenticate
    redirect_to root_path unless customer_signed_in?
  end
  def logind
    redirect_to home_top_select_path if customer_signed_in?
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<main role="main">
  <div class="container marketing">
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-5">
        <%= image_tag 'logo.png' , size: "500x500"%>
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">友達と遊ぶ場所を共有したいという想いから<br>このアプリを作成しました</h2>
      </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
      <div class="col-md-5 order-md-1">
         <%= image_tag 'logo.png' , size: "300x300"%>
      </div>
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">グループを作成する</h2>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-5">
         <%= image_tag 'logo.png' , size: "300x300"%>
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">友達が加入する</h2>
      </div>
    </div>
    <div class="row featurette">
      <div class="col-md-5">
         <%= image_tag 'logo.png' , size: "300x300"%>
      </div>
      <div class="col-md-7">
        <h2 class="featurette-heading">場所をグループに投稿する</h2>
      </div>
    </div>
    <div class="row featurette">
      <div class="col-md-12">
        <h2 class="featurette-heading">さぁ、始めてみよう！！</h2>
        <%= link_to '新規登録', new_customer_registration_path, class: "btn btn-info"%>
        <%= link_to 'ゲストログイン', customers_guest_sign_in_path, method: :post, class: "btn btn-success"%>
        <%= link_to 'ログイン', new_customer_session_path, class: "btn btn-warning"%>
      </div>
    </div>

app/views/homes/top.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 home_top">
			<div class="home_top__header">
				<div class="home_top__logo">
					<%= image_tag 'logo.png' %>
				</div>
				<div class="home_top_link">
					<%= link_to '新規登録', new_customer_registration_path %>
				</div>
				<div class="home_top_link">
					<%= link_to 'ログイン', new_customer_session_path%>
				</div>
				<div class="home_top_link">
					<%= link_to 'ゲストログイン', customers_guest_sign_in_path, method: :post%>
				</div>
			</div>
		</div>
	</div>
	<div class="row home_top_demo">
		<div class="col-md-6 home_left">
			<div class="home_left__sentence">
				<h1>みんなで作れる<br>
				好きな場所だけのマップ</h1>
				<p>グループを作ってメンバーとシェアすることもできます。<br>
			私たちだけのオリジナルマップが、今すぐはじめられます。</p>
				<%= link_to '登録してみよう', new_customer_registration_path%>
			</div>
		</div>
		<div class="col-md-6 home_right">
			<%= image_tag 'home/top3.png' %>
		</div>
	</div>
	<div class="row home_middle">
		<div class="col-md-6 home_middle_left">
			<div class="home_middle_left_sentence">
				<h1>オリジナルマップが<br>
				驚くほどかんたんに</h1>
				<p>パソコンでもスマートフォンでも<br>
				簡単に個性的なマップが作成できます</p>
				<%= link_to 'お試しログイン', customers_guest_sign_in_path, method: :post%>
			</div>
		</div>
		<div class="col-md-6 home_middle_right">
			<div class="element js-animation">
				<%= image_tag 'home/top1.png' %>
			</div>
		</div>
	</div>
	<%= javascript_include_tag "home_top.js" %>

</div>

app/views/homes/top_select.html.erb
<div class="container shore_margin">
	<div class="row">
		<%= render 'layouts/customer_header'%>
		<%= render 'layouts/customer_profile'%>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<div class="home_top_select">
				<div class="home_top_select__link">
					<div class="home_top_select__link">
						<div class="home_top_select__link_box">
							<div class="home_top_select__link_item">
								<%= link_to 'スポット一覧', public_places_path,  class: "btn btn-info"%>
							</div>
							<div class="home_top_select__link_item">
								<%= link_to 'スポット登録', new_public_place_path, class: "btn btn-success"%>
							</div>
						</div>
						<div class="home_top_select__link_box">
							<div class="home_top_select__link_item">
								<%= link_to 'グループ一覧', public_groups_customers_path, class: "btn btn-warning"%>
							</div>
							<div class="home_top_select__link_item">
								<%= link_to '会員一覧', public_customers_path, class: "btn btn-danger"%>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>