config/routes.rb
Rails.application.routes.draw do
  # カスタマーroutes
  root 'homes#top'
  get 'home/top', to: 'homes#top'
  get 'home/about', to: 'homes#about'
  get 'home/top_select', to: 'homes#top_select'
  devise_for :customers
  namespace :public do
    resources :customers, only: [:index, :show, :edit, :update] do
      member do
        get 'confirm', to: 'customers#confirm'
        put "withdrawal" => "customers#withdrawal"
      end
    end
    resources :inquiries, only: [:index, :create]
    resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :groups_customers, only: [:index, :create, :destroy] do
      member do
        get 'menbers', to: 'groups_customers#members_index'
        get 'maps', to: 'groups_customers#maps_index'
        get 'key_word', to: 'groups_customers#key_word'
      end
    end
    resources :places do
      resources :likes, only: [:create, :destroy]
      member do
        get 'place_new_add', to: 'places#place_new_add'
      end
    end
    resources :place_images
  end

  # 管理者routes
  devise_for :admins
  namespace :admin do
    resources :inquiries, only: [:index, :edit, :update]
    resources :customers, only: [:index, :show] do
      member do
        get 'confirm', to: 'customers#confirm'
        put "withdrawal" => "customers#withdrawal"
      end
    end
    resources :genres, only: [:index, :edit, :create, :destroy, :update]
    resources :groups, only: [:index, :show, :destroy]
    resources :places, only: [:index, :show, :destroy]
  end

  # ゲストログイン用
  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'customers/sessions#new_guest'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :places, dependent: :destroy
  has_many :genres, dependent: :destroy
  has_many :groups_customers, dependent: :destroy

  # 3文字以上
  validates :nick_name, length: { minimum: 3 }

  # 一意性
  validates :nick_name, uniqueness: true

  # お問い合わせ
  has_many :inquiries, dependent: :destroy

  # いいね機能
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :place
  def already_liked?(place)
    likes.exists?(place_id: place.id)
  end

  # 画像アップロード機能
  attachment :image

  # 退会済みならログイン不可
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ゲストログイン用
  def self.guest
    find_or_create_by!(email: 'guest@gmail.work', nick_name: "げすと") do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :places, dependent: :destroy

  # 空白NG
  validates :name, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :places, dependent: :destroy
  has_many :groups_customers, dependent: :destroy

  # 空白NG
  validates :name, presence: true
  # validates :is_closed, presence: true

  # 一意性
  validates :name, uniqueness: true
  # validates :key_word, uniqueness: true, allow_nil: true

  # 画像アップロード機能
  attachment :image

  # is_closed(非公開の場合)のみ空白NG
  with_options if: :is_closed? do
    validates :key_word, presence: true
  end
end

app/models/groups_customer.rb
class GroupsCustomer < ApplicationRecord
  belongs_to :customer
  belongs_to :group

  # 空白NG
  # validates :customer_id, presence: true
  # validates :group_id, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :customer
  enum status: { 対応待ち: 0, 対応中: 1, 対応済み: 2 }

  # 空白NG
  validates :customer_id, presence: true
  validates :title, presence: true
  validates :body, presence: true
  validates :status, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :place

  # 空白NG
  validates :customer_id, presence: true
  validates :place_id, presence: true

  # いいね機能
  validates_uniqueness_of :place_id, scope: :customer_id
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :genre
  belongs_to :customer

  # group_idを持たなくても保存できる
  belongs_to :group, optional: true

  # 複数画像投稿用
  has_many :place_images, dependent: :destroy
  accepts_attachments_for :place_images, attachment: :image

  # 3文字以上
  validates :address, length: { minimum: 3 }

  # 空白NG
  validates :customer_id, presence: true
  validates :place_name, presence: true

  # 経度、緯度表示機能
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # いいね機能
  has_many :likes
  has_many :liked_customers, through: :likes, source: :customer
end

app/models/place_image.rb
class PlaceImage < ApplicationRecord
  belongs_to :place, optional: true
  # 画像投稿用
  attachment :image

  # place_idの空白NG
  validates :place_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # 新規登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    home_top_select_path
  end

  # ログイン後のリダイレクト先
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_inquiries_path
    when Customer
      home_top_select_path
    end
  end

  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate, only: [:top_select]
  before_action :logind, only: [:top]
  def top
  end

  def about
  end

  def top_select
    @gorups = GroupsCustomer.where(customer_id: current_customer.id)
    @places = Place.where(customer_id: current_customer.id)
  end

  private
  # ログインしていないユーザーはTOPページに遷移
  def authenticate
    redirect_to root_path unless customer_signed_in?
  end
  def logind
    redirect_to home_top_select_path if customer_signed_in?
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_admin_header.html.erb
<div class="col-lg-3">
	<header>
		<div>
			<%= image_tag 'logo.png' %>
		</div>
		<% if admin_signed_in? %>
			<div class="link"><%= link_to '会員一覧', admin_customers_path%></div>
			<div class="link"><%= link_to 'スポット一覧', admin_places_path%></div>
			<div class="link"><%= link_to 'グループ一覧', admin_groups_path%></div>
			<div class="link"><%= link_to 'ジャンル一覧', admin_genres_path%></div>
			<div class="link"><%= link_to 'お問い合わせ一覧', admin_inquiries_path%></div>
			<div class="link"><%= link_to 'ログアウト',  destroy_admin_session_path, method: :delete %></div>
		<% else %>
			<div class="link"><%= link_to 'ログイン', new_admin_session_path%></div>
		<% end %>
	</header>
</div>

app/views/layouts/_customer_footer.html.erb
<div class="row">
	<footer>
	    <div class="link"><%= link_to 'お問い合わせ', new_public_inquiry_path %></div>
	</footer>
</div>

app/views/layouts/_customer_header.html.erb
<div class="row">
  <div class="col-md-12">
    <header>
    <!-- ゲストアカウントの場合 -->
      <% if current_customer.nick_name == "げすと" %>
              <div id="header" class="header">
              <%= image_tag 'logo.png' %>
                <ul class="header__link_signed_in">
                  <li class="link"><%= link_to 'マイページ', public_customer_path(current_customer.id) %></li>
                  <li class="link"><%= link_to 'トップページ', home_top_select_path %></li>
                  <li class="link"><%= link_to 'スポット一覧', public_places_path %></li>
                  <li class="link"><%= link_to 'スポット登録', new_public_place_path %></li>
                  <li class="link"><%= link_to 'グループ一覧', public_groups_customers_path %></li>
                  <li class="link"><%= link_to 'お問い合わせ', public_inquiries_path%></li>
                  <li class="link"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete %></li>
                </ul>
                <div class="phone_header">
                  <ul class="phone_header_link">
                    <li class="link"><%= link_to 'マイページ', public_customer_path(current_customer.id) %></li>
                    <li class="link"><%= link_to 'トップページ', home_top_select_path %></li>
                    <li class="link"><%= link_to 'お問い合わせ', public_inquiries_path%></li>
                    <li class="link"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete %></li>
                  </ul>
                </div>
              </div>
      <% else %>
        <!-- ログインしている場合 -->
        <% if customer_signed_in? %>
            <div id="header" class="header">
            <%= image_tag 'logo.png' , size: "200x200"%>
                  <ul class="header__link_signed_in">
                    <li class="link"><%= link_to 'トップページ', home_top_select_path %></li>
                    <li class="link"><%= link_to 'スポット一覧', public_places_path %></li>
                    <li class="link"><%= link_to 'スポット登録', new_public_place_path %></li>
                    <li class="link"><%= link_to 'グループ一覧', public_groups_customers_path %></li>
                    <li class="link"><%= link_to 'グループ作成', new_public_group_path %></li>
                    <li class="link"><%= link_to 'お問い合わせ', public_inquiries_path%></li>
                    <li class="link"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete %></li>
                  </ul>
              <div class="phone_header">
                <ul class="phone_header_link">
                  <li class="link"><%= link_to 'マイページ', public_customer_path(current_customer.id) %></li>
                  <li class="link"><%= link_to 'トップページ', home_top_select_path %></li>
                  <li class="link"><%= link_to 'お問い合わせ', public_inquiries_path%></li>
                  <li class="link"><%= link_to 'ログアウト',  destroy_customer_session_path, method: :delete %></li>
                </ul>
              </div>
            </div>
        <% else %>
        <!-- ログインしていない場合 -->
            <%= image_tag 'logo.png' , size: "200x200"%>
            <div class="header">
              <ul class="header__link_unsign">
                <li class="link"><%= link_to 'トップページ', root_path %></li>
                <li class="link"><%= link_to 'About', home_about_path %></li>
                <li class="link"><%= link_to '会員一覧', public_customers_path%></li>
                <li class="link"><%= link_to '新規登録', new_customer_registration_path %></li>
                <li class="link"><%= link_to 'ログイン', new_customer_session_path%></li>
              </ul>
            </div>
        <% end %>
      <% end %>
    </header>
  </div>
</div>

app/views/layouts/_customer_profile.html.erb
<div class="row">
  <div class="col-md-12 customer_profile">
    <div class="customer_profile_main">
      <div>
        <%= attachment_image_tag current_customer, :image, :fill, 100, 100, format: 'jpg', fallback: "profile.png", size:'100x100' ,class: "img-circle"%>
      </div>
      <div>
        <h3>ようこそ!!<br><span><%= current_customer.nick_name%>さん</span></h3>
      </div>
      <% if current_customer.nick_name == "げすと"%>
        <div>
          <a href="#" class="btn btn-success" disabled="disabled">グループ加入するには<br>新規登録が必要です</a>
        </div>
      <% else %>
      <!-- グループに加入していない場合 -->
        <% if GroupsCustomer.where(customer_id: current_customer.id).blank?%>
          <div>
            <%= link_to "グループを探そう", public_groups_customers_path,class: "btn btn-info"%>
          </div>
        <% else %>
          <div>
            <h3>加入しているグループ</h3>
              <ul>
                <% GroupsCustomer.includes([:group]).where(customer_id: current_customer.id).each do |group_customer|%>
                  <li><%= link_to group_customer.group.name, public_group_path(group_customer.group.id)%></li>
              <% end %>
              </ul>
          </div>
        <% end %>
      <% end %>
        <!-- スポット登録が無い場合 -->
        <% if Place.where(customer_id: current_customer.id).blank?%>
          <div>
            <%= link_to "スポット登録してみよう", new_public_place_path,class: "btn btn-info"%>
          </div>
        <% else %>
          <div>
            <h3>スポット登録数</h3>
            <%= link_to public_customer_path(current_customer.id), class: "btn btn-info" do %>
              <%= Place.where(customer_id: current_customer.id).count%>件
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_phone_footer.html.erb
<footer>
	<div class="footer">
	<!-- ゲストログイン用 -->
	<% if current_customer.nick_name == "げすと" %>
		<!-- マップ一覧 -->
		<div class="footer_link">
			<%= link_to public_places_path do %>
				<i class="fas fa-map-marked-alt footer_icon"></i>
				<br><span>スポット一覧</span>
			<% end %>
		</div>
		<!-- マップ作成 -->
		<div class="footer_link">
			<%= link_to new_public_place_path do %>
				<i class="fas fa-map-marker-alt footer_icon"></i>
				<br><span>スポット登録</span>
			<% end %>
		</div>
		<!-- グループ一覧 -->
		<div class="footer_link">
			<%= link_to public_groups_customers_path do %>
				<i class="fas fa-users footer_icon"></i>
				<br><span>グループ一覧</span>
			<% end %>
		</div>
	<% else %>
	<!-- 通常会員用 -->
		<!-- マップ一覧 -->
		<div class="footer_link">
			<%= link_to public_places_path do %>
				<i class="fas fa-map-marked-alt footer_icon"></i>
				<br><span>スポット一覧</span>
			<% end %>
		</div>
		<!-- マップ作成 -->
		<div class="footer_link">
			<%= link_to new_public_place_path do %>
				<i class="fas fa-map-marker-alt footer_icon"></i>
				<br><span>スポット登録</span>
			<% end %>
		</div>
		<!-- グループ一覧 -->
		<div class="footer_link">
			<%= link_to public_groups_customers_path do %>
				<i class="fas fa-users footer_icon"></i>
				<br><span>グループ一覧</span>
			<% end %>
		</div>
		<!-- グループ作成 -->
		<div class="footer_link">
			<%= link_to new_public_group_path do %>
				<i class="fab fa-creative-commons-by footer_icon"></i>
				<br><span>グループ作成</span>
			<% end %>
		</div>



	<% end %>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <script src="https://kit.fontawesome.com/761a0b56dd.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Share</title>
  </head>

  <body>
    <%= yield %>
    <div id="page-top" class="blogicon-chevron-up"><i class="fas fa-angle-double-up"></i></div>
    <%= javascript_include_tag "home_scroll.js" %>
  </body>
</html>